theme: jekyll-theme-minimal
# baseurl: https://mufid.github.io/rubydarinol
collections:
  episodes:
    layout: episodes
    output: true
defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episodes"
